Project_Take_two/Models/CurrentDateTimeProvider.cs
namespace Project_Take_two.Models
{
    public class CurrentDateTimeProvider:IDateTimeProvider
    {
        public DateTime Actual()
        {
            return DateTime.Now;
        }

        
    }
}

Project_Take_two/Models/EnumExtension.cs
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace Project_Take_two.Models
{
    static public class EnumExtensions
    {
        public static string GetDisplayName(this Enum enumValue)
        {
            return enumValue.GetType()
                            .GetMember(enumValue.ToString())
                            .First()
                            .GetCustomAttribute<DisplayAttribute>()
                            .GetName();
        }
    }
}

Project_Take_two/Models/ErrorViewModel.cs
namespace Project_Take_two.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Project_Take_two/Models/Guides.cs
using System.ComponentModel.DataAnnotations;
namespace Project_Take_two.Models
{
    public enum Guides
    {
        [Display(Name = "Grzegorz")]Grzegorz =1,
        [Display(Name = "Maciek")] Maciek =2,
        [Display(Name = "Kamil")] Kamil =3,
        [Display(Name = "Baca")] Baca =4
    }
}

Project_Take_two/Models/IDateTimeProvider.cs
namespace Project_Take_two.Models
{
    public interface IDateTimeProvider
    {
        DateTime Actual();
    }
}

Project_Take_two/Models/ITravelService.cs
namespace Project_Take_two.Models
{
    public interface ITravelService
    {
        int Add(Travel trip);
        void Delete(int id);
        void Update(Travel trip);
        List<Travel> FindAll();
        Travel? FindById(int id);
        int Count();
    }
}

Project_Take_two/Models/MemoryTravelService.cs
namespace Project_Take_two.Models
{
    public class MemoryTravelService : ITravelService
    {
        private Dictionary<int, Travel> _items = new Dictionary<int, Travel>();
        IDateTimeProvider _timeProvider;

        public MemoryTravelService(IDateTimeProvider timeProvider)
        {
            _timeProvider = timeProvider;
        }

        public int Add(Travel item)
        {
            int id = _items.Keys.Count != 0 ? _items.Keys.Max() : 0;
            item.Id = id + 1;
            item.Created = _timeProvider.Actual();
            _items.Add(item.Id, item);
            return item.Id;
        }

        public int Count()
        {
            return _items.Count;
        }
        public void Delete(int id)
        {
            _items.Remove(id);
        }

        public List<Travel> FindAll()
        {
            return _items.Values.ToList();
        }

        public Travel? FindById(int id)
        {
            return _items[id];
        }

        public void Update(Travel item)
        {
            _items[item.Id] = item;
        }
    }
}

Project_Take_two/Models/Travel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Project_Take_two.Models
{
    public class Travel
    {
       


        [HiddenInput]
        public int Id { get; set; }

        [Required(ErrorMessage = "Proszę podać nazwe!")]
        [StringLength(maximumLength: 100, ErrorMessage = "Zbyt długia nazwa")]
        public string Name { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Proszę podać date rozpoczęcia!")]
        public DateTime? StartDate { get; set; }

        [DataType(DataType.Date)]
        public DateTime? EndDate { get; set; }

        [Required(ErrorMessage = "Proszę podać miejsce rozpoczęcia!")]
        public string StartPlace { get; set; }

        public string EndPlace { get; set; }

        [Required]
        public string Participants { get; set; }

        [Required]
        [Display(Name = "Guide")]
        public Guides Guide { get; set; }

        [HiddenInput]
        public DateTime Created { get; set; }





    }
}

Project_Take_two/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Project_Take_two.Models;
using System.Diagnostics;

namespace Project_Take_two.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Project_Take_two/Controllers/TravelController.cs
using Microsoft.AspNetCore.Mvc;
using Project_Take_two.Models;
using System.Diagnostics;
using Project_Take_two.Models;
namespace Project_Take_two.Controllers
{
    public class TravelController : Controller
    {

        private readonly ITravelService _travelService;
        public TravelController(ITravelService contactService)
        {
            _travelService = contactService;
        }
        static DateTime tempD1 = new DateTime(2022,10,10);
        static DateTime tempD2 = new DateTime(2022, 10, 15);
        static Travel tt = new Travel();
        
        
        
        public IActionResult Index()
        {
            if(_travelService.Count() == 0)
            {
                tt.Id = 0;
                tt.Name= "Egipt";
                tt.StartPlace = "Kraków";
                tt.EndPlace = "Warszawa";
                tt.StartDate = tempD1;
                tt.EndDate = tempD2;
                tt.Participants = "Kamil";
                tt.Guide = Guides.Grzegorz;
               // _travelService.Add(tt);
            }
            return View(_travelService.FindAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Travel model)
        {
            if(ModelState.IsValid)
            {
                _travelService.Add(model);
                return RedirectToAction("Index");
                
                //zapisz obiekt do bazy/kolekcji albo wykonaj operacje
            }
            return View();
        }
        public IActionResult Details(int id) {
            return View(_travelService.FindById(id));
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_travelService.FindById(id));
        }
        [HttpPost]
        public IActionResult Delete(Travel model)
        {
            _travelService.Delete(model.Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            
                return View(_travelService.FindById(id));
        }
            

        
        [HttpPost]
        public IActionResult Update(Travel model)
        {
            _travelService.Update(model);

            return RedirectToAction("Index");
    }

        /*[HttpGet]
        public String Update(int? id)
        {
            return "Edycja " + id;
        }*/
    }
}

Project_Take_two/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Project_Take_two/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project_Take_two</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project_Take_two.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratorium3_App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Travel" asp-action="Index">Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Travel" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Project_Take_two - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Project_Take_two/Views/Travel/Create.cshtml
@model Travel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Dodawanie Podrózy</h1>
<form asp-controller="Travel" asp-action="Create" method="post" >
    <div class="mb-3">
        <label asp-for="Name">Nazwa</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StartDate">Data Rozpoczęcia</label>
        <input class="form-control" asp-for="StartDate" />
        <span class="text-danger" asp-validation-for="StartDate"></span>
    </div>
    <div class="mb-3">
        <label asp-for="EndDate">Data Zakończenia</label>
        <input class="form-control" asp-for="EndDate" />
        <span class="text-danger" asp-validation-for="EndDate"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StartPlace">Miejsce rozpoczęcia</label>
        <input class="form-control" asp-for="StartPlace" />
        <span class="text-danger" asp-validation-for="StartPlace"></span>
    </div>
    <div class="mb-3">
        <label asp-for="EndPlace">Miejsce zakończenia</label>
        <input class="form-control" asp-for="EndPlace" />
        <span class="text-danger" asp-validation-for="EndPlace"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Participants">Uczestnik</label>
        <input class="form-control" asp-for="Participants" />
        <span class="text-danger" asp-validation-for="Participants"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Guide"></label>
        <select class="form-control" asp-for="Guide" asp-items="@Html.GetEnumSelectList<Guides>()"></select>
        <span class="text-danger" asp-validation-for="Guide"></span>
    </div>
    
    <button class="btn btn-primary" type="submit">Stwórz</button>

</form>

Project_Take_two/Views/Travel/Delete.cshtml
@model Travel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form asp-controller="Travel" asp-action="Delete" method="post">
    <input asp-for="Id" />
    <p>Czy na pewno usunąc</p>
    <button type="submit">Tak</button>
    <a asp-controller="Travel" asp-action="Index">Nie</a>

</form>

Project_Take_two/Views/Travel/Details.cshtml
@model Travel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2>Detale kontaktu @Model.Id</h2>
<table class="table">
    <tr>
        <th>
            Imię
        </th>
        <th>
            Data rozpoczęcia
        </th>
        <th>
            Data zakończenia
        </th>
        <th>
            Miejsce rozpoczęcia
        </th>
        <th>
            Miejsce zakończenia
        </th>
        <th>
            Uczestnicy
        </th>
        <th>
            Przewodnik
        </th>
        <th>
            Time of Creation
        </th>
    </tr>
        <tr>
            <td>
                @Model.Name
            </td>
            <td>
                @Model.StartDate
            </td>
            <td>@Model.EndDate</td>
            <td>@Model.StartPlace</td>
            <td>@Model.EndPlace</td>
            <td>@Model.Participants</td>
            <td>@Model.Guide.GetDisplayName()</td>
            <td>@Model.Created</td>
        </tr>
</table>
<a asp-controller="Travel" asp-action="Index">Powrót</a>

Project_Take_two/Views/Travel/Index.cshtml
@model List<Travel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2>Lista kontaktów</h2>
<table class="table">
    <tr>
        <th>
            Imię
        </th>
        <th>
            Data rozpoczęcia
        </th>
        <th>
            Data zakończenia
        </th>
        <th>
            Miejsce rozpoczęcia
        </th>
        <th>
            Akcje
        </th>
    </tr>
    @foreach (var item in @Model)
    {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.StartDate
            </td>
            <td>@item.EndDate</td>
            <td>@item.StartPlace</td>
            <td>
                <a class="btn btn-primary"
                   asp-action="Update"
                   asp-controller="Travel"
                   asp-route-id=@item.Id>Edytuj</a>
                <a class="btn btn-primary"
                   asp-action="Details"
                   asp-controller="Travel"
                   asp-route-id=@item.Id>Szczegóły</a>
                <a class="btn btn-primary"
                   asp-action="Delete"
                   asp-controller="Travel"
                   asp-route-id=@item.Id>Usuń</a>
            </td>
        </tr>
    }
</table>

Project_Take_two/Views/Travel/Update.cshtml
@model Travel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Edycja kontaktu</h1>
<form asp-controller="Travel" asp-action="Update" method="post">
    <div class="mb-3">
        <label asp-for="Name">Nazwa</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StartDate">Data Rozpoczęcia</label>
        <input class="form-control" asp-for="StartDate" />
        <span class="text-danger" asp-validation-for="StartDate"></span>
    </div>
    <div class="mb-3">
        <label asp-for="EndDate">Data Zakończenia</label>
        <input class="form-control" asp-for="EndDate" />
        <span class="text-danger" asp-validation-for="EndDate"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StartPlace">Miejsce rozpoczęcia</label>
        <input class="form-control" asp-for="StartPlace" />
        <span class="text-danger" asp-validation-for="StartPlace"></span>
    </div>
    <div class="mb-3">
        <label asp-for="EndPlace">Miejsce zakończenia</label>
        <input class="form-control" asp-for="EndPlace" />
        <span class="text-danger" asp-validation-for="EndPlace"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Participants">Uczestnik</label>
        <input class="form-control" asp-for="Participants" />
        <span class="text-danger" asp-validation-for="Participants"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Guide"></label>
        <select class="form-control" asp-for="Guide" asp-items="@Html.GetEnumSelectList<Guides>()"></select>
        <span class="text-danger" asp-validation-for="Guide"></span>
    </div>
    <input class="form-control" asp-for="Created" />

    <button class="btn btn-primary" type="submit">Zapisz</button>
    <button class="btn btn-primary" type="Reset">Resetuj</button>
</form>