Laboratorium2/Models/Birth.cs
using Laboratorium2.Models;
public class Birth
{
    public string imie { get;set; }
    public DateTime uro { get;set; }

    public bool IsValid()
    {
        return imie != null;
    }
    public int Calc()
    {
        DateTime now=DateTime.Now;

        return (int)now.Year-(int)uro.Year;
    }

}

Laboratorium2/Models/Calculator.cs
using Laboratorium2.Controllers;

public class Calculator
    {
        public operators? Operator { get; set; }
        public double? x { get; set; }
        public double? y { get; set; }

        public String Op
        {
            get
            {
                switch (Operator)
                {
                    case operators.ADD:
                        return "+";
                    case operators.SUB:
                        return "-";
                    case operators.MUL: 
                        return "*";
                    case operators.DIV: 
                        return "/"; 
                    default:
                        return "";
                }
            }
        }

        public bool IsValid()
        {
            return Operator != null && x != null && y != null;
        }

        public double Calculate()
        {
            double? result = 0;
            switch (Operator)
            {
                case operators.ADD:
                    result = x + y;
                    break;

                case operators.SUB:
                    result = x - y;
                    break;

                case operators.MUL:
                    result = x * y;
                    break;

                case operators.DIV:
                    result = x / y;
                    break;

                default: return double.NaN;

            }
            return (double)result;
        }
    }

Laboratorium2/Models/ErrorViewModel.cs
namespace Laboratorium2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Laboratorium2/Controllers/BirthController.cs
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium2.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Form()
        {
            return View();
        }
        public IActionResult Result1([FromForm] Birth model)
        {
            if (!model.IsValid())
            {
                return View("Error");
            }
            return View(model);
        }
    }
}

Laboratorium2/Controllers/CalkulatorController.cs
using Microsoft.AspNetCore.Mvc;
using System.Reflection;

/*
 *  1.Wysłanie żądania do formularze (potrzebna akcja w kontrolerze do formularza)
 *  2.wypełnienie formularza i submit 
 *  3.wysłanie żądania z danymi formularza (potrzebna akcja odbierjąca dane)
 *  4.obliczenie i zwrócenie widoku z wynikami
 */
namespace Laboratorium2.Controllers
{
    public enum operators
    {
        ADD, SUB, MUL, DIV
    }
    public class CalkulatorController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Form()
        {
            return View();
        }
        public IActionResult Result1([FromForm] Calculator model)
        {
            if (!model.IsValid())
            {
                return View("Error");
            }
            return View(model);
        }
    }
}

Laboratorium2/Controllers/HomeController.cs
using Laboratorium2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Laboratorium2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Laboratorium2/Views/Birth/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form action="Result1" method="post">
    imie=<input type="text" name="imie" /><br />
    wiek=<input type="date" name="uro"/><br />
    <button type="submit">submit</button>

</form>

Laboratorium2/Views/Birth/Result1.cshtml
@model Birth
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<H3>Cześć @Model.imie, masz @Model.Calc() lat</H3>

Laboratorium2/Views/Calkulator/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form action="Result" method="post">
    x=<input name="x" type="number" step="0.001" />
    <select name="operator">
        <option value="add">+</option>
        <option value="sub">&minus;</option>
        <option value="mul">&times;</option>
        <option value="div">&divide;</option>
    </select>
    y=<input name="y" type="number" step="0.001" /><br />
    <button type="submit">Submit</button>
</form>

Laboratorium2/Views/Calkulator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<H3>@Model.x @Model.Op @Model.y = @Model.Calculate()</H3>

Laboratorium2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorium2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laboratorium2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratorium2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calkulator" asp-action="Form">Calkulator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="Form">Hello</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Laboratorium2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>