Laboratorium3-App/Models/Contact.cs
using Data.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace Laboratorium3_App.Models
{
    public class Contact
    {

        [HiddenInput]
        public int Id { get; set; }

        [Display(Name = "Imię")]
        [Required(ErrorMessage = "Proszę podać imię!")]
        [StringLength(maximumLength: 100, ErrorMessage = "Zbyt długie imie")]
        public string Name { get; set; }

        [RegularExpression(".+\\@.+\\.[a-z]{2,3}")]
        [Required(ErrorMessage = "Proszę podać poprawny eamil!")]
        public string Email { get; set; }

        [Phone(ErrorMessage = "Niepoprawny numer telefonu!!")]
        public string Phone { get; set; }

        [DataType(DataType.Date)]
        public DateTime? Birth { get; set; }

        [Display(Name = "Priorytet")]
        public Priority Priority { get; set; }

        
       
        [HiddenInput]
        public DateTime Created { get; set; }


        public int? OrganizationId { get; set; }

        [ValidateNever]
        public List<SelectListItem> Organizations { get; set; }

    }
}

Laboratorium3-App/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using Laboratorium3_App.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace Laboratorium3_App.Controllers
{
    [Authorize]
    public class ContactController : Controller
    {

        private readonly IContactService _contactService;

        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(_contactService.FindAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            Contact model = new Contact();
            model.Organizations = _contactService.FindAllOrganizations()
                .Select(oe => new SelectListItem()
                {
                    Text=oe.Title,
                    Value=oe.Id.ToString()
                }).ToList();
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(Contact model)
        {
            if (ModelState.IsValid)
            {
                _contactService.Add(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult CreateApi()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateApi(Contact model)
        {
            if (ModelState.IsValid)
            {
                _contactService.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        
        public IActionResult Details(int id) {
            var model=_contactService.FindById(id);
            if(model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_contactService.FindById(id));
        }
        [HttpPost]
        public IActionResult Delete(Contact model)
        {
            _contactService.Delete(model.Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
                return View(_contactService.FindById(id));
            
        }
        [HttpPost]
        public IActionResult Update(Contact model)
        {
            if (ModelState.IsValid)
            {
                _contactService.Update(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public String Edit(int? id)
        {
            return "Edycja " + id;
        }

        public IActionResult PagedIndex(int? page=1,int? size=2)
        {
           return View(_contactService.FindPage((int)page, (int)size));
        }
    }
}

Laboratorium3-App/Controllers/OrganizationsController.cs
using Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium3_App.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class OrganizationsController : ControllerBase
    {
        private readonly AppDbContext _context;

        public OrganizationsController(AppDbContext context)
        {
            _context = context;
        }
        [Route("filter")]
        public IActionResult GetFilterdOrganizations(string query)
        {
            var result = _context.Organizations
                .Where(o => o.Title.ToUpper().StartsWith(query.ToUpper()))
                .Select(o => new
                {
                    Id = o.Id,
                    Name = o.Title
                })
                .ToList();
            return Ok(result);
        }

        [Route("{id}")]
        public IActionResult GetOrganizationById(int id)
        {
            var result = _context.Organizations.Find(id);
            if (result == null)
            {
                return NotFound();
            }
            else
            {
                return Ok(result);
            }



        }
    }
}

Laboratorium3-App/Views/Contact/Create.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Dodawanie kontaktu</h1>
<form asp-controller="Contact" asp-action="Create" method="post" >
    <div class="mb-3">
        <label asp-for="Name">Imię</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email">Email</label>
        <input class="form-control" asp-for="Email" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Birth">Birth</label>
        <input class="form-control" asp-for="Birth" />
        <span class="text-danger" asp-validation-for="Birth"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Phone">Phone</label>
        <input class="form-control" asp-for="Phone" />
        <span class="text-danger" asp-validation-for="Phone"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Priority">Kategoria</label>
        <div>
            <span asp-validation-for="Priority" class="text-danger"></span>
        </div>
        <select class="form-control" asp-for="Priority" asp-items="@Html.GetEnumSelectList<Priority>()"></select>
    </div>
    <div class="mb-3">
        <label asp-for="OrganizationId">Organizations</label>
        <select class="form-control" asp-for="OrganizationId" asp-items="@Model.Organizations"> </select>
    </div>
    <button class="btn btn-primary" type="submit">Stwórz</button>

</form>

Laboratorium3-App/Views/Contact/CreateApi.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Dodawanie kontaktu api</h1>
<form asp-controller="Contact" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Name">Imię</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email">Email</label>
        <input class="form-control" asp-for="Email" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Birth">Birth</label>
        <input class="form-control" asp-for="Birth" />
        <span class="text-danger" asp-validation-for="Birth"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Phone">Phone</label>
        <input class="form-control" asp-for="Phone" />
        <span class="text-danger" asp-validation-for="Phone"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Priority">Kategoria</label>
        <div>
            <span asp-validation-for="Priority" class="text-danger"></span>
        </div>
        <select class="form-control" asp-for="Priority" asp-items="@Html.GetEnumSelectList<Priority>()"></select>
    </div>
    <div class="mb-3">
        <label asp-for="OrganizationId">Organizations</label>
        <label for="filter">Filtr</label>
        <input class="form-control" type="text" id="filter" />
        <label asp-for="OrganizationId"></label>
        <select class="form-control" id="OrganizationId"> </select>
       
    </div>
    <a asp-action="Create" asp-controller="Organizations">Dodaj nową organizacje</a>

</form>
@section Scripts{
    <script>
        const select = document.getElementById("OrganizationId");
        const filter = document.getElementById("filter");
        filter.onchange=function(){
            select.innerHTML="";
            fetch(`/api/organizations/filter?query=${filter.value}`)
            .then(response=>response.json())
            .then(arr=>{
                for(let org of arr){
                    let option=document.createElement('option');
                    option.setAttribute('value',org.id);
                    option.innerText=org.name;
                    select.appendChild(option);
                }
            });
        }
    </script>
}

Laboratorium3-App/Views/Contact/Delete.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form asp-action="Delete" method="post">
    <input asp-for="Id" />
    <p>Czy na pewno usunąc</p>
    <button type="submit">Tak</button>
    <a asp-controller="Contact" asp-action="Index">Nie</a>

</form>

Laboratorium3-App/Views/Contact/Details.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div>
<table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Name
        </th>
        <th>
            Email
        </th>
        <th>
            Phone
        </th>
        <th>
            Birth
        </th>
        <th>
            Priority
        </th>
        <th>
            Time Of Creation
        </th>
    </tr>
    <tr>
        <td>
            @Model.Id
        </td>
        <td>
            @Model.Name
        </td>
        <td>
            @Model.Email
        </td>
        <td>
            @Model.Phone
        </td>
        <td>
            @Model.Birth
        </td>
        <td>
            @Model.Priority
        </td>
        <td>
            @Model.Created
        </td>
    </tr>
</table>
    <a class="btn btn-secondary" asp-controller="Contact" asp-action="Index">Cofnij</a>
</div>

Laboratorium3-App/Views/Contact/Index.cshtml
@model List<Contact>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2>Lista kontaktów</h2>
<table class="table">
    <tr>
        <th>
           Imię
        </th>
        <th>
            Email
        </th>
        <th>
            Priority
        </th>
        <th>
            Akcje
        </th>
    </tr>
    @foreach (var item in @Model)
    {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.Email
            </td>
            <td>
                @*  @item.Priority.GetDisplayName()*@
            </td>
            <td>
                <a class="btn btn-primary"
                   asp-action="Update"
                   asp-controller="Contact"
                   asp-route-id=@item.Id>Edytuj</a>
                <a class="btn btn-primary"
                   asp-action="Details"
                   asp-controller="Contact"
                   asp-route-id=@item.Id>Szczegóły</a>
                <a class="btn btn-primary"
                   asp-action="Delete"
                   asp-controller="Contact"
                   asp-route-id=@item.Id>Usuń</a>
            </td>
        </tr>
    }
</table>

Laboratorium3-App/Views/Contact/PagedIndex.cshtml
@model PagingList<Contact>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2>Lista kontaktów</h2>
<table class="table">
    <tr>
        <th>
            Imię
        </th>
        <th>
            Email
        </th>
        <th>
            Priority
        </th>
        <th>
            Akcje
        </th>
    </tr>
    @foreach (var item in @Model.Data)
    {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.Email
            </td>
            <td>
                @*  @item.Priority.GetDisplayName()*@
            </td>
            <td>
                <a class="btn btn-primary"
                   asp-action="Update"
                   asp-controller="Contact"
                   asp-route-id=@item.Id>Edytuj</a>
                <a class="btn btn-primary"
                   asp-action="Details"
                   asp-controller="Contact"
                   asp-route-id=@item.Id>Szczegóły</a>
                <a class="btn btn-primary"
                   asp-action="Delete"
                   asp-controller="Contact"
                   asp-route-id=@item.Id>Usuń</a>
            </td>
        </tr>
    }
</table>

<nav aria-label="Books page navigation"> 
    <ul class="pagination"> 
        @if (Model.IsPrevious) 
        { 
            <li class="page-item">
            <a class="page-link" 
                asp-controller="Contact" 
                asp-action="PagedIndex" 
                asp-route-page="@(Model.Number - 1)" 
                asp-route-size="2">
            Poprzednia
            </a>
            </li> 
        } 
        else 
        { 
            <li class="page-item disabled">
            <a class="page-link">Poprzednia</a>
            </li> 
        } 
        <li class="page-item disabled">
        <a class="page-link" >@Model.Number</a>
        </li> 
        @if (Model.IsNext) 
        { 
            <li class="page-item">
            <a class="page-link" 
                asp-controller="Contact" 
                asp-action="PagedIndex" 
                asp-route-page="@(Model.Number + 1)" 
                asp-route-size="2">
                Następna
            </a>
            </li> 
        } 
        else 
        { 
            <li class="page-item disabled">
            <a class="page-link">Następna</a>
            </li> 
        } 
    </ul>
</nav>

Laboratorium3-App/Views/Contact/Update.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Edycja kontaktu</h1>
<form asp-controller="Contact" asp-action="Update" method="post">
    <div class="mb-3">
        <label asp-for="Name">Imię</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email">Email</label>
        <input class="form-control" asp-for="Email" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Birth">Birth</label>
        <input class="form-control" asp-for="Birth" />
        <span class="text-danger" asp-validation-for="Birth"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Phone">Phone</label>
        <input class="form-control" asp-for="Phone" />
        <span class="text-danger" asp-validation-for="Phone"></span>
    </div>
    <div>
        <label asp-for="Priority">Kategoria</label>
        <div>
            <span asp-validation-for="Priority" class="text-danger"></span>
        </div>
        <select class="form-control" asp-for="Priority" asp-items="@Html.GetEnumSelectList<Priority>()"></select>
    </div>
   
        <input class="form-control" asp-for="Created" /> 
     
    

    <button class="btn btn-primary" type="submit">Zapisz</button>

</form>